name: Workflow

on:
  push:
    branches: ['main']

jobs:
  Client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

  Server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: installing dependencies 
        run: npm install
        working-directory: ./server

      - name: Run Server
        run: npm test
        working-directory: ./server