name:Workflow

on:
  push:
    branches: ['main']
	Jobs:

	Client:

		Runs-on : ubuntu-latest

			Steps:

				working-directory: ./client
				Uses : actions/checkout@v4

				Name : install dependencies
					Run : npm install
				Name : Build
					Run: npm run build  


	Server :

		Runs-on :ubuntu-latest


			Steps:
			
				working-directory: ./server
				Uses: actions/checkout@v4

				Name : installing dependencies 
					Run : npm install

      	Name: Run Server
        	run: npm test
					

